server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: sergiocuacor
    password: password
    url: jdbc:postgresql://localhost:5432/customer # Nombre de la BD a la que nos tenemos que conectar
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
# Micrometer tracing config
management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields: x-request-id
      correlation:
        fields: x-request-id
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    io.micrometer.tracing: debug
    org.springframework.cloud.openfeign: DEBUG

